pipeline {
    agent any

    triggers {
        // will be triggered every hour
        //cron('H * * * *')
        
        // Will check for changes in the github project to trigger it
        pollSCM('* * * * *')
        
        // If Job job1 or job2 is triggered and finished with success it will trigger this pipeline
        //upstream(upstreamProjects: 'job1,job2', threshold: hudson.model.Result.SUCCESS)
    }
    
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    
    environment { 
        PYTHON_VERSION = '3.9'
    }
    
    stages {
        stage('General') {
            environment { 
                AN_ACCESS_KEY = credentials('slack-token') 
            }
            steps {
                sh 'printenv'
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"

            }
        }
        
        
        stage('SCM Poll') {
            //agent { dockerfile true }
            steps {
                //git 'https://github.com/BachirBelkhiri/dockerfile-test.git'
                sh 'ls -ali'                
            }
            
            post {
                success {
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: '#008000', tokenCredentialId: 'slack-token',  failOnError: true, message: "Git Cloned ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
            }

        }

        stage('Build') {
            agent {
                // Equivalent to "docker build -f Dockerfile.build --build-arg version=1.0.2 ./build/
                dockerfile { 
                    filename 'Dockerfile'
                    dir 'test1'
                 
                    //label 'my-defined-label'
                    //additionalBuildArgs  '--build-arg version=1.0.2'
                    //args '-v /tmp:/tmp'
                    
                    //registryUrl 'https://myregistry.com/'
                    //registryCredentialsId 'myPredefinedCredentialsInJenkins'
                    
                }
            }
            
            steps {
                sh 'node --version'
                sh 'git --version'
                sh 'curl --version'
            }
            
            post {
                //always {
                    // I will always be executed
                    //echo "Hello world"
                //}
                        
                success {
                    // I will be executed if i success
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'good', tokenCredentialId: 'slack-token',  failOnError: true, message: "Build Success ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
                
                failure {
                    // I will be executed if i fail
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'danger', tokenCredentialId: 'slack-token',  failOnError: true, message: "Build Fail ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
                
                //changed {
                    // I will be executed if something chnage from the previous build
                //}
                
                //fixed {
                    // I will be executed if i am fixed from the previous build
                //}
                
                //aborted {
                    // I will be executed if i am aborted
                //}
                
                
            }
            
        }
        
        stage('Fail Test') {
            steps {
                sh 'exit 1'                
            }
            
            post {
                success {
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'good', tokenCredentialId: 'slack-token',  failOnError: true, message: "Test Success ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
                
                failure {
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'danger', tokenCredentialId: 'slack-token',  failOnError: true, message: "Test Failure ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
            }

        }
    }
}
