pipeline {
    agent any

    triggers {
        // will be triggered every hour
        //cron('H * * * *')
        
        // Will check for changes in the github project to trigger it
        pollSCM('* * * * *')
        
        // If Job job1 or job2 is triggered and finished with success it will trigger this pipeline
        //upstream(upstreamProjects: 'job1,job2', threshold: hudson.model.Result.SUCCESS)
    }

    stages {
        
        stage('SCM Poll') {
            //agent { dockerfile true }
            steps {
                //git 'https://github.com/BachirBelkhiri/dockerfile-test.git'
                sh 'ls -ali'
            }
            
            post {
                success {
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: '#008000', tokenCredentialId: 'slack-token',  failOnError: true, message: "Git Cloned ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
            }

        }

        stage('Build') {
            agent {
                // Equivalent to "docker build -f Dockerfile.build --build-arg version=1.0.2 ./build/
                dockerfile { 
                    filename 'Dockerfile'
                    dir 'test1'
                 
                    //label 'my-defined-label'
                    //additionalBuildArgs  '--build-arg version=1.0.2'
                    //args '-v /tmp:/tmp'
                    
                    //registryUrl 'https://myregistry.com/'
                    //registryCredentialsId 'myPredefinedCredentialsInJenkins'
                    
                }
            }
            
            steps {
                sh 'node --version'
                sh 'git --version'
                sh 'curl --version'
            }
            
            post {
                //always {
                    // I will always be executed
                    //echo "Hello world"
                //}
                        
                success {
                    // I will be executed if i success
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'good', tokenCredentialId: 'slack-token',  failOnError: true, message: "Build Success ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
                
                failure {
                    // I will be executed if i fail
                    slackSend teamDomain: 'letshavesomefundudes', channel: '#devops', color: 'danger', tokenCredentialId: 'slack-token',  failOnError: true, message: "Build Fail ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                }
                
                //changed {
                    // I will be executed if something chnage from the previous build
                //}
                
                //fixed {
                    // I will be executed if i am fixed from the previous build
                //}
                
                //aborted {
                    // I will be executed if i am aborted
                //}
                
                
            }
            
        }
    }
}
