pipeline {
    agent none

    triggers {
        //cron('H * * * *')
        
        pollSCM('* * * * *')

    }

    environment {
        DEPLOY_TEST='true'
        DEPLOY_PROD='false'
    }

    stages {
        stage('Building Dev Branch') {
            
            agent any
            //agent {
            //    label "Slave Linux"
            //}

            when {
                branch 'dev'
                environment name: 'DEPLOY_TEST', value: 'true'

                anyOf {
                    triggeredBy 'SCMTrigger'
                    triggeredBy 'TimerTrigger'
                    triggeredBy 'BuildUpstreamCause'
                }
            }

            steps {
                echo 'Deploying dev branch to test servers'
            }

        }

        stage('Building Master Branch') {

            agent any
            //agent {
            //    label "Slave Linux Prod"
            //}

            when {
                allOf {}

                    branch 'master'
                    environment name: 'DEPLOY_PROD', value: 'true'

                    anyOf {
                        triggeredBy 'SCMTrigger'
                        triggeredBy 'TimerTrigger'
                        triggeredBy 'BuildUpstreamCause'
                    }
                }
            }

            steps {
                echo 'Deploying master branch to prod servers'
            }

        }
        

    }

}